doctrine:
    dbal:
        driver: pdo_pgsql
        server_version: '18'
        charset: utf8
        url: '%env(resolve:DATABASE_URL)%'
        # Register PostGIS custom DBAL types
        types:
            geometry:  Jsor\Doctrine\PostGIS\Types\GeometryType
            geography: Jsor\Doctrine\PostGIS\Types\GeographyType
            raster:    Jsor\Doctrine\PostGIS\Types\RasterType
        mapping_types:
            geometry:  geometry
            geography: geography
            raster:    raster

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src'
                prefix: 'App'
                alias: App

when@test:
    doctrine:
        dbal:
            # Use transactions to roll back test data after each test
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
